const ADD_TO_BASKET = 'ADD_TO_BASKET';
const INCREASE_QUANTITY_BASKET = 'INCREASE_QUANTITY_BASKET';
const DECREASE_QUANTITY_BASKET = 'DECREASE_QUANTITY_BASKET';
const REMOVE_FROM_BASKET = 'REMOVE_FROM_BASKET';
const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';

export {
  ADD_TO_BASKET,
  INCREASE_QUANTITY_BASKET,
  DECREASE_QUANTITY_BASKET,
  ADD_TO_FAVORITES,
  REMOVE_FROM_FAVORITES,
  REMOVE_FROM_BASKET,
};
