const ADD_TO_BASKET = 'ADD_TO_BASKET';
const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';

export { ADD_TO_BASKET, ADD_TO_FAVORITES, REMOVE_FROM_FAVORITES };
