const storeActionType = {
  SET_SELECTED_CATEGORY: 'SET_SELECTED_CATEGORY',
  SET_SELECTED_SUBCATEGORY: 'SET_SELECTED_SUBCATEGORY',
  SEARCH_PRODUCT: 'SEARCH_PRODUCT',
};

export default storeActionType;
